#! /usr/bin/env bash
DL_DIR="$HOME/Downloads"
declare -A DEST=(
    [jpg]=images [jpeg]=images [png]=images [gif]=images
    [pdf]=pdfs [mp4]=video [mp3]=audio
    [txt]=txt
)
while read -r file; do
    if [[ ! -f "$DL_DIR/$file" ]]; then
        continue
    fi
     ext="${file##*.}"
     ext="${ext,,}"
     dest="${DEST[$ext]:-other}"
     mkdir -p "$DL_DIR/$dest"
     mv -n "$DL_DIR/$file" "$DL_DIR/$dest/"
     echo "Flyttade $file till $dest/"
done < <(inotifywait -m -e close_write -e moved_to --format '%f' "$DL_DIR")
